<?php

namespace Firebed\AadeMyData\Enums;

use Firebed\AadeMyData\Enums\Traits\HasLabels;

enum CountryCode: string
{
    use HasLabels;
    
    case AD = "AD";
    case AE = "AE";
    case AF = "AF";
    case AG = "AG";
    case AI = "AI";
    case AL = "AL";
    case AM = "AM";
    case AN = "AN";
    case AO = "AO";
    case AQ = "AQ";
    case AR = "AR";
    case AS = "AS";
    case AT = "AT";
    case AU = "AU";
    case AW = "AW";
    case AX = "AX";
    case AZ = "AZ";
    case BA = "BA";
    case BB = "BB";
    case BD = "BD";
    case BE = "BE";
    case BF = "BF";
    case BG = "BG";
    case BH = "BH";
    case BI = "BI";
    case BJ = "BJ";
    case BL = "BL";
    case BM = "BM";
    case BN = "BN";
    case BO = "BO";
    case BR = "BR";
    case BS = "BS";
    case BT = "BT";
    case BV = "BV";
    case BW = "BW";
    case BY = "BY";
    case BZ = "BZ";
    case CA = "CA";
    case CC = "CC";
    case CD = "CD";
    case CF = "CF";
    case CG = "CG";
    case CH = "CH";
    case CI = "CI";
    case CK = "CK";
    case CL = "CL";
    case CM = "CM";
    case CN = "CN";
    case CO = "CO";
    case CR = "CR";
    case CU = "CU";
    case CV = "CV";
    case CX = "CX";
    case CY = "CY";
    case CZ = "CZ";
    case DE = "DE";
    case DJ = "DJ";
    case DK = "DK";
    case DM = "DM";
    case DO = "DO";
    case DZ = "DZ";
    case EC = "EC";
    case EE = "EE";
    case EG = "EG";
    case EH = "EH";
    case ER = "ER";
    case ES = "ES";
    case ET = "ET";
    case FI = "FI";
    case FJ = "FJ";
    case FK = "FK";
    case FM = "FM";
    case FO = "FO";
    case FR = "FR";
    case GA = "GA";
    case GB = "GB";
    case GD = "GD";
    case GE = "GE";
    case GF = "GF";
    case GG = "GG";
    case GH = "GH";
    case GI = "GI";
    case GL = "GL";
    case GM = "GM";
    case GN = "GN";
    case GP = "GP";
    case GQ = "GQ";
    case GR = "GR";
    case GS = "GS";
    case GT = "GT";
    case GU = "GU";
    case GW = "GW";
    case GY = "GY";
    case HK = "HK";
    case HM = "HM";
    case HN = "HN";
    case HR = "HR";
    case HT = "HT";
    case HU = "HU";
    case ID = "ID";
    case IE = "IE";
    case IL = "IL";
    case IM = "IM";
    case IN = "IN";
    case IO = "IO";
    case IQ = "IQ";
    case IR = "IR";
    case IS = "IS";
    case IT = "IT";
    case JE = "JE";
    case JM = "JM";
    case JO = "JO";
    case JP = "JP";
    case KE = "KE";
    case KG = "KG";
    case KH = "KH";
    case KI = "KI";
    case KM = "KM";
    case KN = "KN";
    case KP = "KP";
    case KR = "KR";
    case KW = "KW";
    case KY = "KY";
    case KZ = "KZ";
    case LA = "LA";
    case LB = "LB";
    case LC = "LC";
    case LI = "LI";
    case LK = "LK";
    case LR = "LR";
    case LS = "LS";
    case LT = "LT";
    case LU = "LU";
    case LV = "LV";
    case LY = "LY";
    case MA = "MA";
    case MC = "MC";
    case MD = "MD";
    case ME = "ME";
    case MF = "MF";
    case MG = "MG";
    case MH = "MH";
    case MK = "MK";
    case ML = "ML";
    case MM = "MM";
    case MN = "MN";
    case MO = "MO";
    case MP = "MP";
    case MQ = "MQ";
    case MR = "MR";
    case MS = "MS";
    case MT = "MT";
    case MU = "MU";
    case MV = "MV";
    case MW = "MW";
    case MX = "MX";
    case MY = "MY";
    case MZ = "MZ";
    case NA = "NA";
    case NC = "NC";
    case NE = "NE";
    case NF = "NF";
    case NG = "NG";
    case NI = "NI";
    case NL = "NL";
    case NO = "NO";
    case NP = "NP";
    case NR = "NR";
    case NU = "NU";
    case NZ = "NZ";
    case OC = "OC";
    case OM = "OM";
    case PA = "PA";
    case PE = "PE";
    case PF = "PF";
    case PG = "PG";
    case PH = "PH";
    case PK = "PK";
    case PL = "PL";
    case PM = "PM";
    case PN = "PN";
    case PR = "PR";
    case PS = "PS";
    case PT = "PT";
    case PW = "PW";
    case PY = "PY";
    case QA = "QA";
    case RE = "RE";
    case RO = "RO";
    case RS = "RS";
    case RU = "RU";
    case RW = "RW";
    case SA = "SA";
    case SB = "SB";
    case SC = "SC";
    case SD = "SD";
    case SE = "SE";
    case SG = "SG";
    case SH = "SH";
    case SI = "SI";
    case SJ = "SJ";
    case SK = "SK";
    case SL = "SL";
    case SM = "SM";
    case SN = "SN";
    case SO = "SO";
    case SR = "SR";
    case ST = "ST";
    case SV = "SV";
    case SY = "SY";
    case SZ = "SZ";
    case TC = "TC";
    case TD = "TD";
    case TF = "TF";
    case TG = "TG";
    case TH = "TH";
    case TJ = "TJ";
    case TK = "TK";
    case TL = "TL";
    case TM = "TM";
    case TN = "TN";
    case TO = "TO";
    case TR = "TR";
    case TT = "TT";
    case TV = "TV";
    case TW = "TW";
    case TZ = "TZ";
    case UA = "UA";
    case UG = "UG";
    case UM = "UM";
    case US = "US";
    case UY = "UY";
    case UZ = "UZ";
    case VA = "VA";
    case VC = "VC";
    case VE = "VE";
    case VG = "VG";
    case VI = "VI";
    case VN = "VN";
    case VU = "VU";
    case WF = "WF";
    case WS = "WS";
    case YE = "YE";
    case YT = "YT";
    case ZA = "ZA";
    case ZM = "ZM";
    case ZW = "ZW";

    public function label(): string
    {
        return match ($this) {
            self::AD => "Ανδόρα",
            self::AE => "Ηνωμένα Αραβικά Εμιράτα",
            self::AF => "Αφγανιστάν",
            self::AG => "Αντίγκουα και Μπαρμπούντα",
            self::AI => "Ανγκουίλα",
            self::AL => "Αλβανία",
            self::AM => "Αρμενία",
            self::AN => "Ολλανδικές Αντίλλες",
            self::AO => "Αγκόλα",
            self::AQ => "Ανταρκτική",
            self::AR => "Αργεντινή",
            self::AS => "Αμερικανική Σαμόα",
            self::AT => "Αυστρία",
            self::AU => "Αυστραλία",
            self::AW => "Αρούμπα",
            self::AX => "Νήσοι Όλαντ",
            self::AZ => "Αζερμπαϊτζάν",
            self::BA => "Βοσνία και Ερζεγοβίνη",
            self::BB => "Μπαρμπάντος",
            self::BD => "Μπαγκλαντές",
            self::BE => "Βέλγιο",
            self::BF => "Μπουρκίνα Φάσο",
            self::BG => "Βουλγαρία",
            self::BH => "Μπαχρέιν",
            self::BI => "Μπουρούντι",
            self::BJ => "Μπενίν",
            self::BL => "Άγιος Βαρθολομαίος",
            self::BM => "Βερμούδες",
            self::BN => "Μπρουνέι",
            self::BO => "Βολιβία",
            self::BR => "Βραζιλία",
            self::BS => "Μπαχάμες",
            self::BT => "Μπουτάν",
            self::BV => "Νήσος Μπουβέ",
            self::BW => "Μποτσουάνα",
            self::BY => "Λευκορωσία",
            self::BZ => "Μπελίζ",
            self::CA => "Καναδάς",
            self::CC => "Νήσοι Κόκος (Κίλινγκ)",
            self::CD => "Κονγκό (Λαϊκή Δημοκρατία του)",
            self::CF => "Κεντροαφρικανική Δημοκρατία",
            self::CG => "Κονγκό",
            self::CH => "Ελβετία",
            self::CI => "Ακτή Ελεφαντοστού",
            self::CK => "Νήσοι Κουκ",
            self::CL => "Χιλή",
            self::CM => "Καμερούν",
            self::CN => "Κίνα",
            self::CO => "Κολομβία",
            self::CR => "Κόστα Ρίκα",
            self::CU => "Κούβα",
            self::CV => "Πράσινο Ακρωτήριο",
            self::CX => "Νήσος των Χριστουγέννων",
            self::CY => "Κύπρος",
            self::CZ => "Τσεχία",
            self::DE => "Γερμανία",
            self::DJ => "Τζιμπουτί",
            self::DK => "Δανία",
            self::DM => "Ντομίνικα",
            self::DO => "Δομινικανή Δημοκρατία",
            self::DZ => "Αλγερία",
            self::EC => "Εκουαδόρ",
            self::EE => "Εσθονία",
            self::EG => "Αίγυπτος",
            self::EH => "Δυτική Σαχάρα",
            self::ER => "Ερυθραία",
            self::ES => "Ισπανία",
            self::ET => "Αιθιοπία",
            self::FI => "Φινλανδία",
            self::FJ => "Φίτζι",
            self::FK => "Νήσοι Φώκλαντ",
            self::FM => "Μικρονησία",
            self::FO => "Νήσοι Φερόες",
            self::FR => "Γαλλία",
            self::GA => "Γκαμπόν",
            self::GB => "Ηνωμένο Βασίλειο",
            self::GD => "Γρενάδα",
            self::GE => "Γεωργία",
            self::GF => "Γαλλική Γουιάνα",
            self::GG => "Γκέρνσεϊ",
            self::GH => "Γκάνα",
            self::GI => "Γιβραλτάρ",
            self::GL => "Γροιλανδία",
            self::GM => "Γκάμπια",
            self::GN => "Γουινέα",
            self::GP => "Γουαδελούπη",
            self::GQ => "Ισημερινή Γουινέα",
            self::GR => "Ελλάδα",
            self::GS => "Νότια Γεωργία και Νότιες Νήσοι Σάντουιτς",
            self::GT => "Γουατεμάλα",
            self::GU => "Γκουάμ",
            self::GW => "Γουινέα-Μπισάου",
            self::GY => "Γουιάνα",
            self::HK => "Χονγκ Κονγκ",
            self::HM => "Νήσος Χερντ και Νήσοι Μακντόναλντ",
            self::HN => "Ονδούρα",
            self::HR => "Κροατία",
            self::HT => "Αϊτή",
            self::HU => "Ουγγαρία",
            self::ID => "Ινδονησία",
            self::IE => "Ιρλανδία",
            self::IL => "Ισραήλ",
            self::IM => "Νήσος του Μαν",
            self::IN => "Ινδία",
            self::IO => "Βρετανικό Έδαφος Ινδικού Ωκεανού",
            self::IQ => "Ιράκ",
            self::IR => "Ιράν",
            self::IS => "Ισλανδία",
            self::IT => "Ιταλία",
            self::JE => "Τζέρσεϊ",
            self::JM => "Τζαμάικα",
            self::JO => "Ιορδανία",
            self::JP => "Ιαπωνία",
            self::KE => "Κένυα",
            self::KG => "Κιργιζία",
            self::KH => "Καμπότζη",
            self::KI => "Κιριμπάτι",
            self::KM => "Κομόρες",
            self::KN => "Άγιος Χριστόφορος και Νέβις",
            self::KP => "Βόρεια Κορέα",
            self::KR => "Νότια Κορέα",
            self::KW => "Κουβέιτ",
            self::KY => "Νήσοι Κέιμαν",
            self::KZ => "Καζακστάν",
            self::LA => "Λάος",
            self::LB => "Λίβανος",
            self::LC => "Άγιος Λουκίας",
            self::LI => "Λιχτενστάιν",
            self::LK => "Σρι Λάνκα",
            self::LR => "Λιβερία",
            self::LS => "Λεσότο",
            self::LT => "Λιθουανία",
            self::LU => "Λουξεμβούργο",
            self::LV => "Λετονία",
            self::LY => "Λιβύη",
            self::MA => "Μαρόκο",
            self::MC => "Μονακό",
            self::MD => "Μολδαβία",
            self::ME => "Μαυροβούνιο",
            self::MF => "Άγιος Μαρτίνος (Γαλλικό τμήμα)",
            self::MG => "Μαδαγασκάρη",
            self::MH => "Νήσοι Μάρσαλ",
            self::MK => "Βόρεια Μακεδονία",
            self::ML => "Μάλι",
            self::MM => "Μιανμάρ",
            self::MN => "Μογγολία",
            self::MO => "Μακάο",
            self::MP => "Βόρειες Μαριάνες Νήσοι",
            self::MQ => "Μαρτινίκα",
            self::MR => "Μαυριτανία",
            self::MS => "Μοντσεράτ",
            self::MT => "Μάλτα",
            self::MU => "Μαυρίκιος",
            self::MV => "Μαλδίβες",
            self::MW => "Μαλάουι",
            self::MX => "Μεξικό",
            self::MY => "Μαλαισία",
            self::MZ => "Μοζαμβίκη",
            self::NA => "Ναμίμπια",
            self::NC => "Νέα Καληδονία",
            self::NE => "Νίγηρας",
            self::NF => "Νήσος Νόρφολκ",
            self::NG => "Νιγηρία",
            self::NI => "Νικαράγουα",
            self::NL => "Ολλανδία",
            self::NO => "Νορβηγία",
            self::NP => "Νεπάλ",
            self::NR => "Ναουρού",
            self::NU => "Νιούε",
            self::NZ => "Νέα Ζηλανδία",
            self::OC => "Ωκεανία",
            self::OM => "Ομάν",
            self::PA => "Παναμάς",
            self::PE => "Περού",
            self::PF => "Γαλλική Πολυνησία",
            self::PG => "Παπούα Νέα Γουινέα",
            self::PH => "Φιλιππίνες",
            self::PK => "Πακιστάν",
            self::PL => "Πολωνία",
            self::PM => "Σαιν Πιερ και Μικελόν",
            self::PN => "Νήσοι Πίτκαιρν",
            self::PR => "Πουέρτο Ρίκο",
            self::PS => "Παλαιστίνη",
            self::PT => "Πορτογαλία",
            self::PW => "Παλάου",
            self::PY => "Παραγουάη",
            self::QA => "Κατάρ",
            self::RE => "Ρεϊνιόν",
            self::RO => "Ρουμανία",
            self::RS => "Σερβία",
            self::RU => "Ρωσία",
            self::RW => "Ρουάντα",
            self::SA => "Σαουδική Αραβία",
            self::SB => "Νήσοι Σολομώντος",
            self::SC => "Σεϋχέλλες",
            self::SD => "Σουδάν",
            self::SE => "Σουηδία",
            self::SG => "Σιγκαπούρη",
            self::SH => "Νήσος Αγίας Ελένης",
            self::SI => "Σλοβενία",
            self::SJ => "Σβάλμπαρντ και Γιαν Μαγιέν",
            self::SK => "Σλοβακία",
            self::SL => "Σιέρα Λεόνε",
            self::SM => "Άγιος Μαρίνος",
            self::SN => "Σενεγάλη",
            self::SO => "Σομαλία",
            self::SR => "Σουρινάμ",
            self::ST => "Σάο Τομέ και Πρίνσιπε",
            self::SV => "Ελ Σαλβαδόρ",
            self::SY => "Συρία",
            self::SZ => "Σουαζιλάνδη",
            self::TC => "Νήσοι Τερκς και Κάικος",
            self::TD => "Τσαντ",
            self::TF => "Γαλλικά Νότια και Ανταρκτικά Εδάφη",
            self::TG => "Τόγκο",
            self::TH => "Ταϊλάνδη",
            self::TJ => "Τατζικιστάν",
            self::TK => "Τοκελάου",
            self::TL => "Ανατολικό Τιμόρ",
            self::TM => "Τουρκμενιστάν",
            self::TN => "Τυνησία",
            self::TO => "Τόνγκα",
            self::TR => "Τουρκία",
            self::TT => "Τρινιντάντ και Τομπάγκο",
            self::TV => "Τουβαλού",
            self::TW => "Ταϊβάν",
            self::TZ => "Τανζανία",
            self::UA => "Ουκρανία",
            self::UG => "Ουγκάντα",
            self::UM => "Απομακρυσμένες Νησίδες Ηνωμένων Πολιτειών",
            self::US => "Ηνωμένες Πολιτείες",
            self::UY => "Ουρουγουάη",
            self::UZ => "Ουζμπεκιστάν",
            self::VA => "Άγιος Μαρίνος",
            self::VC => "Άγιος Βικέντιος και Γρεναδίνες",
            self::VE => "Βενεζουέλα",
            self::VG => "Βρετανικές Παρθένοι Νήσοι",
            self::VI => "Αμερικανικές Παρθένοι Νήσοι",
            self::VN => "Βιετνάμ",
            self::VU => "Βανουάτου",
            self::WF => "Ουάλις και Φουτούνα",
            self::WS => "Σαμόα",
            self::YE => "Υεμένη",
            self::YT => "Μαγιότ",
            self::ZA => "Νότια Αφρική",
            self::ZM => "Ζάμπια",
            self::ZW => "Ζιμπάμπουε",
        };
    }
}