<?php

namespace Firebed\AadeMyData\Enums;

enum CurrencyCode: string
{
    use HasLabels;

    case AED = "AED"; // United Arab Emirates Dirham
    case AFN = "AFN"; // Afghan Afghani
    case ALL = "ALL"; // Albanian Lek
    case AMD = "AMD"; // Armenian Dram
    case ANG = "ANG"; // Netherlands Antillean Guilder
    case AOA = "AOA"; // Angolan Kwanza
    case ARS = "ARS"; // Argentine Peso
    case AUD = "AUD"; // Australian Dollar
    case AWG = "AWG"; // Aruban Florin
    case AZN = "AZN"; // Azerbaijani Manat
    case BAM = "BAM"; // Bosnia and Herzegovina Convertible Mark
    case BBD = "BBD"; // Barbadian Dollar
    case BDT = "BDT"; // Bangladeshi Taka
    case BGN = "BGN"; // Bulgarian Lev
    case BHD = "BHD"; // Bahraini Dinar
    case BIF = "BIF"; // Burundian Franc
    case BMD = "BMD"; // Bermudian Dollar
    case BND = "BND"; // Brunei Dollar
    case BOB = "BOB"; // Bolivian Boliviano
    case BOV = "BOV"; // Bolivian Mvdol (funds code)
    case BRL = "BRL"; // Brazilian Real
    case BSD = "BSD"; // Bahamian Dollar
    case BTN = "BTN"; // Bhutanese Ngultrum
    case BWP = "BWP"; // Botswana Pula
    case BYR = "BYR"; // Belarusian Ruble
    case BZD = "BZD"; // Belize Dollar
    case CAD = "CAD"; // Canadian Dollar
    case CDF = "CDF"; // Congolese Franc
    case CHF = "CHF"; // Swiss Franc
    case CLF = "CLF"; // Chilean Unit of Account (UF)
    case CLP = "CLP"; // Chilean Peso
    case CNY = "CNY"; // Chinese Yuan
    case COP = "COP"; // Colombian Peso
    case COU = "COU"; // Colombian Real Value Unit
    case CRC = "CRC"; // Costa Rican Colón
    case CUC = "CUC"; // Cuban Convertible Peso
    case CUP = "CUP"; // Cuban Peso
    case CVE = "CVE"; // Cape Verdean Escudo
    case CZK = "CZK"; // Czech Koruna
    case DJF = "DJF"; // Djiboutian Franc
    case DKK = "DKK"; // Danish Krone
    case DOP = "DOP"; // Dominican Peso
    case DZD = "DZD"; // Algerian Dinar
    case EEK = "EEK"; // Estonian Kroon (before Euro)
    case EGP = "EGP"; // Egyptian Pound
    case ERN = "ERN"; // Eritrean Nakfa
    case ETB = "ETB"; // Ethiopian Birr
    case EUR = "EUR"; // Euro
    case FJD = "FJD"; // Fijian Dollar
    case FKP = "FKP"; // Falkland Islands Pound
    case GBP = "GBP"; // British Pound Sterling
    case GEL = "GEL"; // Georgian Lari
    case GHS = "GHS"; // Ghanaian Cedi
    case GIP = "GIP"; // Gibraltar Pound
    case GMD = "GMD"; // Gambian Dalasi
    case GNF = "GNF"; // Guinean Franc
    case GTQ = "GTQ"; // Guatemalan Quetzal
    case GWP = "GWP"; // Guinea-Bissau Peso
    case GYD = "GYD"; // Guyanese Dollar
    case HKD = "HKD"; // Hong Kong Dollar
    case HNL = "HNL"; // Honduran Lempira
    case HRK = "HRK"; // Croatian Kuna
    case HTG = "HTG"; // Haitian Gourde
    case HUF = "HUF"; // Hungarian Forint
    case IDR = "IDR"; // Indonesian Rupiah
    case ILS = "ILS"; // Israeli New Shekel
    case INR = "INR"; // Indian Rupee
    case IQD = "IQD"; // Iraqi Dinar
    case IRR = "IRR"; // Iranian Rial
    case ISK = "ISK"; // Icelandic Króna
    case JMD = "JMD"; // Jamaican Dollar
    case JOD = "JOD"; // Jordanian Dinar
    case JPY = "JPY"; // Japanese Yen
    case KES = "KES"; // Kenyan Shilling
    case KGS = "KGS"; // Kyrgyzstani Som
    case KHR = "KHR"; // Cambodian Riel
    case KMF = "KMF"; // Comorian Franc
    case KPW = "KPW"; // North Korean Won
    case KRW = "KRW"; // South Korean Won
    case KWD = "KWD"; // Kuwaiti Dinar
    case KYD = "KYD"; // Cayman Islands Dollar
    case KZT = "KZT"; // Kazakhstani Tenge
    case LAK = "LAK"; // Lao Kip
    case LBP = "LBP"; // Lebanese Pound
    case LKR = "LKR"; // Sri Lankan Rupee
    case LRD = "LRD"; // Liberian Dollar
    case LSL = "LSL"; // Lesotho Loti
    case LTL = "LTL"; // Lithuanian Litas (before Euro)
    case LVL = "LVL"; // Latvian Lats (before Euro)
    case LYD = "LYD"; // Libyan Dinar
    case MAD = "MAD"; // Moroccan Dirham
    case MDL = "MDL"; // Moldovan Leu
    case MGA = "MGA"; // Malagasy Ariary
    case MKD = "MKD"; // Macedonian Denar
    case MMK = "MMK"; // Myanmar Kyat
    case MNT = "MNT"; // Mongolian Tögrög
    case MOP = "MOP"; // Macanese Pataca
    case MRO = "MRO"; // Mauritanian Ouguiya (before 2018)
    case MUR = "MUR"; // Mauritian Rupee
    case MVR = "MVR"; // Maldivian Rufiyaa
    case MWK = "MWK"; // Malawian Kwacha
    case MXN = "MXN"; // Mexican Peso
    case MXV = "MXV"; // Mexican Unidad de Inversion (UDI)
    case MYR = "MYR"; // Malaysian Ringgit
    case MZN = "MZN"; // Mozambican Metical
    case NAD = "NAD"; // Namibian Dollar
    case NGN = "NGN"; // Nigerian Naira
    case NIO = "NIO"; // Nicaraguan Córdoba
    case NOK = "NOK"; // Norwegian Krone
    case NPR = "NPR"; // Nepalese Rupee
    case NZD = "NZD"; // New Zealand Dollar
    case OMR = "OMR"; // Omani Rial
    case PAB = "PAB"; // Panamanian Balboa
    case PEN = "PEN"; // Peruvian Sol
    case PGK = "PGK"; // Papua New Guinean Kina
    case PHP = "PHP"; // Philippine Peso
    case PKR = "PKR"; // Pakistani Rupee
    case PLN = "PLN"; // Polish Złoty
    case PYG = "PYG"; // Paraguayan Guaraní
    case QAR = "QAR"; // Qatari Riyal
    case RON = "RON"; // Romanian Leu
    case RSD = "RSD"; // Serbian Dinar
    case RUB = "RUB"; // Russian Ruble
    case RWF = "RWF"; // Rwandan Franc
    case SAR = "SAR"; // Saudi Riyal
    case SBD = "SBD"; // Solomon Islands Dollar
    case SCR = "SCR"; // Seychellois Rupee
    case SDG = "SDG"; // Sudanese Pound
    case SEK = "SEK"; // Swedish Krona
    case SGD = "SGD"; // Singapore Dollar
    case SHP = "SHP"; // Saint Helena Pound
    case SLL = "SLL"; // Sierra Leonean Leone
    case SOS = "SOS"; // Somali Shilling
    case SRD = "SRD"; // Surinamese Dollar
    case STD = "STD"; // São Tomé and Príncipe Dobra (before 2018)
    case SVC = "SVC"; // Salvadoran Colón
    case SYP = "SYP"; // Syrian Pound
    case SZL = "SZL"; // Eswatini Lilangeni
    case THB = "THB"; // Thai Baht
    case TJS = "TJS"; // Tajikistani Somoni
    case TMT = "TMT"; // Turkmenistani Manat
    case TND = "TND"; // Tunisian Dinar
    case TOP = "TOP"; // Tongan Paʻanga
    case TRY = "TRY"; // Turkish Lira
    case TTD = "TTD"; // Trinidad and Tobago Dollar
    case TVD = "TVD"; // Tuvaluan Dollar (unofficial)
    case TWD = "TWD"; // New Taiwan Dollar
    case TZS = "TZS"; // Tanzanian Shilling
    case UAH = "UAH"; // Ukrainian Hryvnia
    case UGX = "UGX"; // Ugandan Shilling
    case USD = "USD"; // United States Dollar
    case UYU = "UYU"; // Uruguayan Peso
    case UZS = "UZS"; // Uzbekistani Som
    case VEF = "VEF"; // Venezuelan Bolívar (before 2018)
    case VND = "VND"; // Vietnamese Đồng
    case VUV = "VUV"; // Vanuatu Vatu
    case WST = "WST"; // Samoan Tala
    case XAF = "XAF"; // Central African CFA Franc
    case XCD = "XCD"; // East Caribbean Dollar
    case XOF = "XOF"; // West African CFA Franc
    case XPD = "XPD"; // Palladium (one troy ounce)
    case XPF = "XPF"; // CFP Franc (used in French Pacific territories)
    case YER = "YER"; // Yemeni Rial
    case ZAR = "ZAR"; // South African Rand
    case ZMK = "ZMK"; // Zambian Kwacha (before 2013)
    case ZWL = "ZWL"; // Zimbabwean Dollar (2009)

    public function label(): string
    {
        return match ($this) {
            // Συμπλήρωσε τα ονόματα
            self::AED => "Ντιρχάμ των Ηνωμένων Αραβικών Εμιράτων",
            self::AFN => "Αφγανή Αφγανιστάν",
            self::ALL => "Λεκ Αλβανίας",
            self::AMD => "Ντραμ Αρμενίας",
            self::ANG => "Γκίλντα Ολλανδικών Αντιλλών",
            self::AOA => "Κουάνζα Αγκόλας",
            self::ARS => "Πέσο Αργεντινής",
            self::AUD => "Δολάριο Αυστραλίας",
            self::AWG => "Φλορίνι Αρούμπα",
            self::AZN => "Μανάτ Αζερμπαϊτζάν",
            self::BAM => "Μάρκο Βοσνίας-Ερζεγοβίνης",
            self::BBD => "Δολάριο Μπαρμπάντος",
            self::BDT => "Τάκα Μπαγκλαντές",
            self::BGN => "Λεβ Βουλγαρίας",
            self::BHD => "Δηνάριο Μπαχρέιν",
            self::BIF => "Φράγκο Μπουρούντι",
            self::BMD => "Δολάριο Βερμούδων",
            self::BND => "Δολάριο Μπρουνέι",
            self::BOB => "Μπολιβιάνο Βολιβίας",
            self::BOV => "Mvdol Βολιβίας",
            self::BRL => "Ρεάλ Βραζιλίας",
            self::BSD => "Δολάριο Μπαχαμών",
            self::BTN => "Νγκούλτρουμ Μπουτάν",
            self::BWP => "Πούλα Μποτσουάνα",
            self::BYR => "Ρούβλι Λευκορωσίας",
            self::BZD => "Δολάριο Μπελίζ",
            self::CAD => "Δολάριο Καναδά",
            self::CDF => "Φράγκο Κονγκό",
            self::CHF => "Φράγκο Ελβετίας",
            self::CLF => "Unidades de fomento Χιλής",
            self::CLP => "Πέσο Χιλής",
            self::CNY => "Γιουάν Κίνας",
            self::COP => "Πέσο Κολομβίας",
            self::COU => "Unidad de Valor Real Κολομβίας",
            self::CRC => "Κολόν Κόστα Ρίκα",
            self::CUC => "Μετατρέψιμο πέσο Κούβας",
            self::CUP => "Πέσο Κούβας",
            self::CVE => "Εσκούδο Πράσινου Ακρωτηρίου",
            self::CZK => "Κορόνα Τσεχίας",
            self::DJF => "Φράγκο Τζιμπουτί",
            self::DKK => "Κορόνα Δανίας",
            self::DOP => "Πέσο Δομινικανής Δημοκρατίας",
            self::DZD => "Δηνάριο Αλγερίας",
            self::EEK => "Κρούνα Εσθονίας",
            self::EGP => "Λίρα Αιγύπτου",
            self::ERN => "Νάκφα Ερυθραίας",
            self::ETB => "Μπιρ Αιθιοπίας",
            self::EUR => "Ευρώ",
            self::FJD => "Δολάριο Φίτζι",
            self::FKP => "Λίρα Νήσων Φόκλαντ",
            self::GBP => "Λίρα Στερλίνα",
            self::GEL => "Λάρι Γεωργίας",
            self::GHS => "Σέντι Γκάνας",
            self::GIP => "Λίρα Γιβραλτάρ",
            self::GMD => "Νταλάσι Γκάμπιας",
            self::GNF => "Φράγκο Γουινέας",
            self::GTQ => "Κετσάλ Γουατεμάλας",
            self::GWP => "Πέσο Γουινέας-Μπισσάου",
            self::GYD => "Δολάριο Γουιάνας",
            self::HKD => "Δολάριο Χονγκ Κονγκ",
            self::HNL => "Λεμπίρα Ονδούρας",
            self::HRK => "Κούνα Κροατίας",
            self::HTG => "Γκουρντ Αϊτής",
            self::HUF => "Φιορίνι Ουγγαρίας",
            self::IDR => "Ρουπία Ινδονησίας",
            self::ILS => "Νέο Σέκελ Ισραήλ",
            self::INR => "Ρουπία Ινδίας",
            self::IQD => "Δηνάριο Ιράκ",
            self::IRR => "Ριάλ Ιράν",
            self::ISK => "Κορόνα Ισλανδίας",
            self::JMD => "Δολάριο Τζαμάικας",
            self::JOD => "Δηνάριο Ιορδανίας",
            self::JPY => "Γιεν Ιαπωνίας",
            self::KES => "Σελίνι Κένυας",
            self::KGS => "Σομ Κιργιζίας",
            self::KHR => "Ρίελ Καμπότζης",
            self::KMF => "Φράγκο Κομόρων",
            self::KPW => "Γουόν Βόρειας Κορέας",
            self::KRW => "Γουόν Νότιας Κορέας",
            self::KWD => "Δηνάριο Κουβέιτ",
            self::KYD => "Δολάριο Νήσων Κέιμαν",
            self::KZT => "Τένγκε Καζακστάν",
            self::LAK => "Κιπ Λάος",
            self::LBP => "Λίρα Λιβάνου",
            self::LKR => "Ρουπία Σρι Λάνκα",
            self::LRD => "Δολάριο Λιβερίας",
            self::LSL => "Λότι Λεσότο",
            self::LTL => "Λίτας Λιθουανίας",
            self::LVL => "Λατς Λετονίας",
            self::LYD => "Δηνάριο Λιβύης",
            self::MAD => "Ντιράμ Μαρόκου",
            self::MDL => "Λέου Μολδαβίας",
            self::MGA => "Αριάρι Μαδαγασκάρης",
            self::MKD => "Δηνάριο Βόρειας Μακεδονίας",
            self::MMK => "Κιάτ Μιανμάρ",
            self::MNT => "Τουγκρίκ Μογγολίας",
            self::MOP => "Πατάκα Μακάο",
            self::MRO => "Ουγκίγια Μαυριτανίας",
            self::MUR => "Ρουπία Μαυρίκιου",
            self::MVR => "Ρουφίγια Μαλδίβων",
            self::MWK => "Κουάτσα Μαλάουι",
            self::MXN => "Πέσο Μεξικού",
            self::MXV => "Unidad de Inversion Μεξικού",
            self::MYR => "Ρινγκίτ Μαλαισίας",
            self::MZN => "Μετικάλ Μοζαμβίκης",
            self::NAD => "Δολάριο Ναμίμπιας",
            self::NGN => "Νάιρα Νιγηρίας",
            self::NIO => "Κόρδοβα Νικαράγουας",
            self::NOK => "Κορόνα Νορβηγίας",
            self::NPR => "Ρουπία Νεπάλ",
            self::NZD => "Δολάριο Νέας Ζηλανδίας",
            self::OMR => "Ριάλ Ομάν",
            self::PAB => "Μπαλμπόα Παναμά",
            self::PEN => "Σολ Περού",
            self::PGK => "Κίνα Παπούας Νέας Γουινέας",
            self::PHP => "Πέσο Φιλιππίνων",
            self::PKR => "Ρουπία Πακιστάν",
            self::PLN => "Ζλότι Πολωνίας",
            self::PYG => "Γκουαρανί Παραγουάης",
            self::QAR => "Ριάλ Κατάρ",
            self::RON => "Λέου Ρουμανίας",
            self::RSD => "Δηνάριο Σερβίας",
            self::RUB => "Ρούβλι Ρωσίας",
            self::RWF => "Φράγκο Ρουάντας",
            self::SAR => "Ριάλ Σαουδικής Αραβίας",
            self::SBD => "Δολάριο Νήσων Σολομώντος",
            self::SCR => "Ρουπία Σεϋχελλών",
            self::SDG => "Λίρα Σουδάν",
            self::SEK => "Κορόνα Σουηδίας",
            self::SGD => "Δολάριο Σιγκαπούρης",
            self::SHP => "Λίρα Αγίας Ελένης",
            self::SLL => "Λεόνε Σιέρα Λεόνε",
            self::SOS => "Σελίνι Σομαλίας",
            self::SRD => "Δολάριο Σουρινάμ",
            self::STD => "Ντόμπρα Σάο Τομέ και Πρίνσιπε",
            self::SVC => "Κολόν Ελ Σαλβαδόρ",
            self::SYP => "Λίρα Συρίας",
            self::SZL => "Λιλανγκένι Σουαζιλάνδης",
            self::THB => "Μπατ Ταϊλάνδης",
            self::TJS => "Σομόνι Τατζικιστάν",
            self::TMT => "Μανάτ Τουρκμενιστάν",
            self::TND => "Δηνάριο Τυνησίας",
            self::TOP => "Παάνγκα της Τόνγκα",
            self::TRY => "Λίρα Τουρκίας",
            self::TTD => "Δολάριο Τρινιντάντ και Τομπάγκο",
            self::TVD => "Δολάριο Τουβαλού",
            self::TWD => "Νέο δολάριο Ταϊβάν",
            self::TZS => "Σελίνι Τανζανίας",
            self::UAH => "Ρίβνια Ουκρανίας",
            self::UGX => "Σελίνι Ουγκάντας",
            self::USD => "Δολάριο Ηνωμένων Πολιτειών",
            self::UYU => "Πέσο Ουρουγουάης",
            self::UZS => "Σομ Ουζμπεκιστάν",
            self::VEF => "Μπολιβάρ Βενεζουέλας",
            self::VND => "Ντονγκ Βιετνάμ",
            self::VUV => "Βατού Βανουάτου",
            self::WST => "Τάλα του Σαμόα",
            self::XAF => "Φράγκο CFA Κεντρικής Αφρικής",
            self::XCD => "Δολάριο Ανατολικής Καραϊβικής",
            self::XOF => "Φράγκο CFA Δυτικής Αφρικής",
            self::XPD => "Παλάδιο",
            self::XPF => "Φράγκο CFP",
            self::YER => "Ριάλ Υεμένης",
            self::ZAR => "Ραντ Νότιας Αφρικής",
            self::ZMK => "Κουάτσα Ζάμπιας",
            self::ZWL => "Δολάριο Ζιμπάμπουε",
        };
    }
}
